#!/usr/bin/env bash

source ./scripts/env "$@"
./scripts/print-env

if [ -z "${ZKPOW_OUT_DIR}" ]; then
  echo "ZKPOW_OUT_DIR is not set"
  exit 1
fi

if [ "${ZKPOW_BUILD:-true}" ]; then
  ./scripts/build.sh
fi

LOG="$ZKPOW_OUT_DIR/run.log"
RUN_LOG="$ZKPOW_LOG_DIR/run.log"
mkdir -p "$ZKPOW_LOG_DIR"
mkdir -p "$ZKPOW_OUT_DIR"

if command -v bat >/dev/null  2>&1; then
  ./target/release/zkpow-host | tee -a "$LOG" "$RUN_LOG"
else
  ./target/release/zkpow-host > >(tee -a "$LOG" "$RUN_LOG") 2> >(tee -a "$LOG" "$RUN_LOG" >&2)
fi
