#!/usr/bin/env bash

source ./scripts/env

if [ "${BUILD:-true}" ]; then
  ./scripts/build-prover.sh
fi

export LOG="$RUN_DIR/run.log"
mkdir -p "$(dirname $LOG)"

./target/release/zkpow-host | tee &>"$LOG"
