#!/usr/bin/env sh

if [ -n "${BASH_SOURCE-}" ]; then
  SCRIPT_PATH="$BASH_SOURCE"
else
  SCRIPT_PATH="$0"
fi

ROOT="$(cd "$(dirname "$SCRIPT_PATH")/.." >/dev/null 2>&1 && pwd)"
export ROOT

# Load environment variables from .env file if it exists
if [ -f "${ENV_FILE:=$ROOT/.env}" ]; then
  # shellcheck source=../.env
  . "$ENV_FILE"
fi

TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
export RUN_DIR="${RUN_DIR:-$ROOT/profiling/runs/$TIMESTAMP}"
export OUT_DIR

# Defaults
export NUM_HEADERS="${NUM_HEADERS:-2016}"
export MAX_BATCHES="${MAX_BATCHES:-1000}"
export RUST_LOG="${RUST_LOG:-info}"
export RUST_LOGGER=flat
export RUST_BACKTRACE="${RUST_BACKTRACE:-1}"
export GUEST_PROFILING="${GUEST_PROFILING:-0}"

export TRACE_FILE="${TRACE_FILE:-trace.json}"
export TRACE_SAMPLE_RATE="${TRACE_FILE:-100}"
export SP1_ENABLE_TOKIO_CONSOLE="${TRACE_FILE:-true}"
export sp1_core="${sp1_core:=}"
